### ISSUE TITLE
Android P :: SavedInstanceState change

### ISSUE THREAD

**Issue by martijnvm** [icapps/android-template-kotlin-viewmodel#1]
Starting Android P, onSavedInstanceState will be called after onStop so clearing the list of ViewModels in the onStop might be not a good idea. 

source: https://developer.android.com/reference/android/app/Activity.html#onSaveInstanceState(android.os.Bundle)

**Comment by maartenvang** [comment]
Good catch! I'll clear them right after saving the state.
